### ISSUE TITLE
State change on reply to resolved ticket

### ISSUE THREAD

**Issue by erocs** [Pentom/modmail_ticketmanager#6]
Just leaving this here before I head out for the day so I don't forget.

After using RT a bit, the flow of a ticket seems to end at resolved, as we wouldn't want to delete a ticket in case the user ever replies to it again in the future (a finished ban term is the obvious case). If the user makes another reply to the modmail thread, can the script detect that and migrate the resolved ticket's status back to open?

**Comment by Pentom** [comment]
Yeah, thats possible.

It seems like a brief algorithm would be:
- Add new function 'reopenTicket' that takes a ticketid and checks if status = SomeVariableStatus.  If it matches, it transitions it to a new state {"Status"} based on some other variable.
- on handleMessageReplies under 'addTicketComment' make call to a reopenTicket if the reply author is NOT the modmailbot.

This could result in a bit more chattyness on the api call level but seems to be less likely to cause a problem.

Might have time to look at this tomorrow.

**Comment by Pentom** [comment]
Feature added, see above notes on how to use.  Tested and it comes through fine.  Be aware that replies from the modmail bot itself (whatever reddit account is in this file) will not reopen the ticket because that would be silly.  This will introduce a tiny bit more time when processing replies but I think it will be necessary.  Theres a minor optimization path that we can take here if it moves processing time too far but not desired quite yet.
